---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _data
  label: Data
  create: all
  match: "**/*"
  new_doc_ext: yml
- type: directory
  path: _category
  label: Category
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: ''
public_path: https://res.cloudinary.com/dwr9rwmo1/image/upload
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
